<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096370839745 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 50")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 50&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 50"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546276 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546285 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546294 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546303 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546313 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546322 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546334 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546344 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546353 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546362 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546371 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546381 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546390 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546399 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546409 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546418 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546427 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376546436 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376611982 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376611992 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376612001 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096376612010 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096408266020 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096595767614 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
<report><version>2</version><sessionid>f8587027cbe0a4a45e77888d</sessionid><type>desync</type><sku>ea.maxis.sims4.13.pc</sku><createtime>2020-03-22 17:49:48</createtime><buildsignature>Local.Unknown.Unknown.1.61.15.1520-1.340.000.24.Release</buildsignature><categoryid>enum.py:166</categoryid><desyncid>f8587027cbe0a4a45e77888d</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Sim 201548096717993197 failed to load (KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10")&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 110, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 552, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1424, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 228, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 76, in load_households&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 162, in _load_household_from_household_proto&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 36, in __call__&#13;&#10;KeyError: 10&#13;&#10;&#13;&#10;During handling of the above exception, another exception occurred:&#13;&#10;&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household.py", line 1270, in load_data&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2997, in load_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 38, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\enum.py", line 166, in _get_unknown_value&#13;&#10;KeyError: "&lt;enum &lt;class 'int'&gt;: SimInfoLODLevel&gt; does not have value 10"&#13;&#10;rtim=0</desyncdata></report>
</root>